"""API Module

An abstraction of the requests made externally
"""

from datetime import datetime, timedelta
from enum import Enum, auto
from typing import Any

import httpx

from devops_final_frontend.models import Api, Auth, Token


class ResponseType(Enum):
    """Types of configurations generated by the LLM"""

    NO_RESPONSE = auto()
    ENV_FILE = auto()
    COMPOSE_FILE = auto()


class ApiService:
    """
    Utility Class that encapsulates backend api calls into service operations
    """

    def __init__(self, api: Api, auth: Auth, token: Token | None):
        self.api: Api = api
        self.auth: Auth = auth
        self.token: Token | None = token
        self.auth_url = f"{self.auth.host}/realms/{self.auth.realm}/protocol/openid-connect/token"

    def is_api_up(self) -> bool:
        """
        Check if the LLM API is available by calling the root endpoint.
        If connection cannot be established consider the api down

        Returns:
            bool: whether or not the api is up
        """

        with httpx.Client(follow_redirects=True) as client:
            try:
                client.get(f"{self.api.host}/version")
                return True
            except httpx.HTTPError:
                return False

    def is_keycloak_up(self) -> bool:
        """
        Check if the Keycloack Instance is available by calling the root endpoint.
        If connection cannot be established consider the api down

        For the management service on 9000, the health check path is '/health/ready'
        but if you are using the base url, '/' is sufficient but it requires disabling
        the raise for status since the root path leads to a chain of redirects

        Returns:
            bool: whether or not the api is up
        """

        with httpx.Client() as client:
            try:
                client.get(self.auth.aux_host, timeout=2)
                # r.raise_for_status()
                return True
            except httpx.HTTPError:
                return False

    def get_compose_get(self, raw_values: dict[str, Any]) -> list[dict[str, int | str]]:
        """
        Invoke the LLM Compose generation Endpoint

        Args:
            raw_values (dict[str, Any]): the params as retrieved from session state

        Returns:
            list[dict[str, int|str]]: the LLM API response
        """

        if not self.token:
            raise httpx.HTTPError("No auth token")

        with httpx.Client(follow_redirects=True, timeout=180) as client:
            r = client.post(
                f"{self.api.host}/{self.api.version}/gen/compose",
                headers={"Authorization": f"Bearer {self.token.access_token}"},
                json={
                    "services": raw_values["services"],
                    "network_name": raw_values["network"]["name"],
                    "network_exists": raw_values["network"]["exists"],
                    "volume_mount": raw_values["volume_mount"],
                },
            )

            r.raise_for_status()
            return r.json()

    def get_token(self) -> Token:
        """
        Authenticate the streamlit app with the backend keycloak instance

        Returns:
            Token: the token retrieved from the backend auth provider
        """

        with httpx.Client() as client:
            r = client.post(
                self.auth_url,
                data={
                    "grant_type": "password",
                    "username": self.auth.username,
                    "password": self.auth.password,
                    "client_id": self.auth.client_id,
                    "client_secret": self.auth.client_secret,
                },
            )

            r.raise_for_status()
            data = r.json()
            return Token(
                access_token=data["access_token"],
                access_exp=datetime.now() + timedelta(seconds=data["expires_in"]),
                refresh_token=data["refresh_token"],
                refresh_exp=datetime.now() + timedelta(seconds=data["refresh_expires_in"]),
            )

    def refresh_token(self) -> Token:
        """
        Refresh the app's token with the backend keycloak instance

        Returns:
            Token: the token retrieved from the backend auth provider
        """

        if not self.token:
            raise httpx.HTTPError("No auth token")

        with httpx.Client() as client:
            r = client.post(
                self.auth_url,
                data={
                    "grant_type": "refresh_token",
                    "refresh_token": self.token.refresh_token,
                    "client_id": self.auth.client_id,
                    "client_secret": self.auth.client_secret,
                },
            )

            r.raise_for_status()
            data = r.json()
            return Token(
                access_token=data["access_token"],
                access_exp=datetime.now() + timedelta(seconds=data["expires_in"]),
                refresh_token=data["refresh_token"],
                refresh_exp=datetime.now() + timedelta(seconds=data["refresh_expires_in"]),
            )
